import type { InsertAchievement } from "@shared/schema";

// Achievement seed data for gamification
export const achievementsSeed: Omit<InsertAchievement, "id" | "createdAt">[] = [
  // ===== STARTER ACHIEVEMENTS (Common) =====
  {
    key: "first_habit",
    name: "Getting Started",
    description: "Create your first habit",
    icon: "🌱",
    rarity: "common",
    category: "starter",
    xpReward: 10,
    requirement: { type: "habits_created", value: 1 },
    order: 1,
  },
  {
    key: "first_completion",
    name: "First Step",
    description: "Complete your first habit",
    icon: "✅",
    rarity: "common",
    category: "starter",
    xpReward: 10,
    requirement: { type: "completions", value: 1 },
    order: 2,
  },
  {
    key: "first_week",
    name: "Week Warrior",
    description: "Complete habits for 7 days in a row",
    icon: "📅",
    rarity: "common",
    category: "starter",
    xpReward: 50,
    requirement: { type: "streak", value: 7 },
    order: 3,
  },
  {
    key: "habit_collector",
    name: "Habit Collector",
    description: "Create 5 different habits",
    icon: "📚",
    rarity: "common",
    category: "starter",
    xpReward: 30,
    requirement: { type: "habits_created", value: 5 },
    order: 4,
  },
  {
    key: "category_creator",
    name: "Organized Mind",
    description: "Create your first category",
    icon: "🗂️",
    rarity: "common",
    category: "starter",
    xpReward: 20,
    requirement: { type: "categories_created", value: 1 },
    order: 5,
  },

  // ===== STREAK ACHIEVEMENTS (Rare) =====
  {
    key: "streak_14",
    name: "Two Week Wonder",
    description: "Maintain a 14-day streak",
    icon: "🔥",
    rarity: "rare",
    category: "dedication",
    xpReward: 100,
    requirement: { type: "streak", value: 14 },
    order: 10,
  },
  {
    key: "streak_30",
    name: "Month Master",
    description: "Achieve a 30-day streak",
    icon: "🌟",
    rarity: "rare",
    category: "dedication",
    xpReward: 200,
    requirement: { type: "streak", value: 30 },
    order: 11,
  },
  {
    key: "streak_100",
    name: "Century Streak",
    description: "Incredible! 100 days in a row!",
    icon: "💯",
    rarity: "epic",
    category: "dedication",
    xpReward: 500,
    requirement: { type: "streak", value: 100 },
    order: 12,
  },
  {
    key: "streak_365",
    name: "Year of Habits",
    description: "Legendary! Complete 365 days!",
    icon: "👑",
    rarity: "legendary",
    category: "dedication",
    xpReward: 1000,
    requirement: { type: "streak", value: 365 },
    order: 13,
  },

  // ===== CONSISTENCY ACHIEVEMENTS (Rare) =====
  {
    key: "perfect_day",
    name: "Perfect Day",
    description: "Complete all your habits in one day",
    icon: "⭐",
    rarity: "rare",
    category: "consistency",
    xpReward: 50,
    requirement: { type: "perfect_day", value: 1 },
    order: 20,
  },
  {
    key: "perfect_week",
    name: "Flawless Week",
    description: "Complete all habits for 7 days straight",
    icon: "💎",
    rarity: "epic",
    category: "consistency",
    xpReward: 300,
    requirement: { type: "perfect_week", value: 1 },
    order: 21,
  },
  {
    key: "perfect_month",
    name: "Unstoppable",
    description: "30 perfect days in a row!",
    icon: "🏆",
    rarity: "legendary",
    category: "consistency",
    xpReward: 800,
    requirement: { type: "perfect_month", value: 1 },
    order: 22,
  },

  // ===== MILESTONES (Rare/Epic) =====
  {
    key: "completions_50",
    name: "Half Century",
    description: "Complete 50 total habits",
    icon: "🎯",
    rarity: "rare",
    category: "milestone",
    xpReward: 100,
    requirement: { type: "total_completions", value: 50 },
    order: 30,
  },
  {
    key: "completions_100",
    name: "Centurion",
    description: "Reach 100 total completions",
    icon: "🎖️",
    rarity: "rare",
    category: "milestone",
    xpReward: 150,
    requirement: { type: "total_completions", value: 100 },
    order: 31,
  },
  {
    key: "completions_500",
    name: "Habit Hero",
    description: "500 completions! You're dedicated!",
    icon: "🦸",
    rarity: "epic",
    category: "milestone",
    xpReward: 400,
    requirement: { type: "total_completions", value: 500 },
    order: 32,
  },
  {
    key: "completions_1000",
    name: "Legend",
    description: "1000 habits completed! Legendary status!",
    icon: "🌠",
    rarity: "legendary",
    category: "milestone",
    xpReward: 1000,
    requirement: { type: "total_completions", value: 1000 },
    order: 33,
  },

  // ===== VARIETY ACHIEVEMENTS =====
  {
    key: "habits_10",
    name: "Habit Enthusiast",
    description: "Create 10 different habits",
    icon: "📖",
    rarity: "rare",
    category: "variety",
    xpReward: 80,
    requirement: { type: "habits_created", value: 10 },
    order: 40,
  },
  {
    key: "habits_20",
    name: "Habit Master",
    description: "Manage 20 habits like a pro",
    icon: "🎓",
    rarity: "epic",
    category: "variety",
    xpReward: 200,
    requirement: { type: "habits_created", value: 20 },
    order: 41,
  },
  {
    key: "categories_5",
    name: "Super Organized",
    description: "Create 5 categories",
    icon: "📊",
    rarity: "rare",
    category: "variety",
    xpReward: 100,
    requirement: { type: "categories_created", value: 5 },
    order: 42,
  },

  // ===== TIME-BASED ACHIEVEMENTS =====
  {
    key: "early_bird",
    name: "Early Bird",
    description: "Complete a habit before 6 AM",
    icon: "🌅",
    rarity: "rare",
    category: "special",
    xpReward: 100,
    requirement: { type: "early_completion", value: 1 },
    order: 50,
  },
  {
    key: "night_owl",
    name: "Night Owl",
    description: "Complete a habit after 10 PM",
    icon: "🌙",
    rarity: "rare",
    category: "special",
    xpReward: 100,
    requirement: { type: "late_completion", value: 1 },
    order: 51,
  },
  {
    key: "weekend_warrior",
    name: "Weekend Warrior",
    description: "Complete all habits on both Saturday and Sunday",
    icon: "🎊",
    rarity: "rare",
    category: "special",
    xpReward: 120,
    requirement: { type: "weekend_perfect", value: 1 },
    order: 52,
  },

  // ===== CHALLENGE ACHIEVEMENTS =====
  {
    key: "five_in_one",
    name: "Multitasker",
    description: "Complete 5 different habits in one day",
    icon: "⚡",
    rarity: "rare",
    category: "challenge",
    xpReward: 150,
    requirement: { type: "habits_in_day", value: 5 },
    order: 60,
  },
  {
    key: "ten_in_one",
    name: "Productivity Beast",
    description: "Complete 10 habits in a single day!",
    icon: "🚀",
    rarity: "epic",
    category: "challenge",
    xpReward: 300,
    requirement: { type: "habits_in_day", value: 10 },
    order: 61,
  },

  // ===== LEVEL ACHIEVEMENTS =====
  {
    key: "level_5",
    name: "Rising Star",
    description: "Reach level 5",
    icon: "⭐",
    rarity: "common",
    category: "progression",
    xpReward: 50,
    requirement: { type: "level", value: 5 },
    order: 70,
  },
  {
    key: "level_10",
    name: "Experienced",
    description: "Reach level 10",
    icon: "🌟",
    rarity: "rare",
    category: "progression",
    xpReward: 100,
    requirement: { type: "level", value: 10 },
    order: 71,
  },
  {
    key: "level_25",
    name: "Expert",
    description: "Reach level 25!",
    icon: "💫",
    rarity: "epic",
    category: "progression",
    xpReward: 300,
    requirement: { type: "level", value: 25 },
    order: 72,
  },
  {
    key: "level_50",
    name: "Master",
    description: "Level 50! True mastery achieved!",
    icon: "👑",
    rarity: "legendary",
    category: "progression",
    xpReward: 1000,
    requirement: { type: "level", value: 50 },
    order: 73,
  },

  // ===== SPECIAL ACHIEVEMENTS =====
  {
    key: "comeback",
    name: "Comeback Kid",
    description: "Resume your habit streak after a break",
    icon: "💪",
    rarity: "rare",
    category: "special",
    xpReward: 80,
    requirement: { type: "comeback", value: 1 },
    order: 80,
  },
  {
    key: "journal_writer",
    name: "Reflective Soul",
    description: "Add journal entries to 10 completions",
    icon: "📝",
    rarity: "rare",
    category: "special",
    xpReward: 100,
    requirement: { type: "journals_created", value: 10 },
    order: 81,
  },
  {
    key: "template_user",
    name: "Quick Starter",
    description: "Create a habit from a template",
    icon: "⚡",
    rarity: "common",
    category: "special",
    xpReward: 30,
    requirement: { type: "template_used", value: 1 },
    order: 82,
  },
];
