import type { InsertHabitTemplate } from "@shared/schema";

// Curated habit templates for quick habit creation
export const habitTemplatesSeed: Omit<InsertHabitTemplate, "id" | "createdAt">[] = [
  // ===== MORNING ROUTINES =====
  {
    name: "Morning Meditation",
    description: "Start your day with 10 minutes of mindfulness",
    category: "Morning Routine",
    icon: "brain.head.profile",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["mindfulness", "morning", "meditation"],
    timeSuggestion: "morning",
    estimatedMinutes: 10,
    popularity: 0,
    featured: true,
  },
  {
    name: "Morning Exercise",
    description: "Get moving with 20-30 minutes of exercise",
    category: "Morning Routine",
    icon: "figure.run",
    color: "#EF4444",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["fitness", "morning", "exercise"],
    timeSuggestion: "morning",
    estimatedMinutes: 25,
    popularity: 0,
    featured: true,
  },
  {
    name: "Healthy Breakfast",
    description: "Fuel your day with a nutritious breakfast",
    category: "Morning Routine",
    icon: "fork.knife",
    color: "#F59E0B",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["nutrition", "morning", "health"],
    timeSuggestion: "morning",
    estimatedMinutes: 15,
    popularity: 0,
    featured: false,
  },
  {
    name: "Morning Journaling",
    description: "Write 3 pages of morning thoughts",
    category: "Morning Routine",
    icon: "book.fill",
    color: "#6366F1",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["writing", "morning", "mindfulness"],
    timeSuggestion: "morning",
    estimatedMinutes: 15,
    popularity: 0,
    featured: false,
  },
  {
    name: "No Phone First Hour",
    description: "Start your day without checking your phone",
    category: "Morning Routine",
    icon: "phone.slash",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "hard",
    tags: ["digital-detox", "morning", "focus"],
    timeSuggestion: "morning",
    estimatedMinutes: 60,
    popularity: 0,
    featured: true,
  },

  // ===== HEALTH & FITNESS =====
  {
    name: "Drink 8 Glasses of Water",
    description: "Stay hydrated throughout the day",
    category: "Health & Fitness",
    icon: "drop.fill",
    color: "#06B6D4",
    frequency: "daily",
    targetCount: 8,
    difficulty: "easy",
    tags: ["health", "hydration"],
    timeSuggestion: "anytime",
    estimatedMinutes: null,
    popularity: 0,
    featured: true,
  },
  {
    name: "10,000 Steps",
    description: "Reach your daily step goal",
    category: "Health & Fitness",
    icon: "figure.walk",
    color: "#10B981",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["fitness", "walking", "health"],
    timeSuggestion: "anytime",
    estimatedMinutes: 90,
    popularity: 0,
    featured: true,
  },
  {
    name: "Take Vitamins",
    description: "Don't forget your daily vitamins",
    category: "Health & Fitness",
    icon: "pills.fill",
    color: "#F59E0B",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["health", "nutrition"],
    timeSuggestion: "morning",
    estimatedMinutes: 1,
    popularity: 0,
    featured: false,
  },
  {
    name: "Yoga Session",
    description: "Practice yoga for flexibility and peace",
    category: "Health & Fitness",
    icon: "figure.mind.and.body",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["fitness", "flexibility", "mindfulness"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },
  {
    name: "Sleep 8 Hours",
    description: "Get a full night of quality sleep",
    category: "Health & Fitness",
    icon: "bed.double.fill",
    color: "#6366F1",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["sleep", "health", "recovery"],
    timeSuggestion: "evening",
    estimatedMinutes: 480,
    popularity: 0,
    featured: true,
  },
  {
    name: "No Sugar",
    description: "Avoid refined sugar for the day",
    category: "Health & Fitness",
    icon: "x.circle.fill",
    color: "#EF4444",
    frequency: "daily",
    targetCount: 1,
    difficulty: "hard",
    tags: ["nutrition", "health", "diet"],
    timeSuggestion: "anytime",
    estimatedMinutes: null,
    popularity: 0,
    featured: false,
  },

  // ===== PRODUCTIVITY =====
  {
    name: "Deep Work (2 Hours)",
    description: "Focused work without distractions",
    category: "Productivity",
    icon: "brain",
    color: "#F59E0B",
    frequency: "daily",
    targetCount: 1,
    difficulty: "hard",
    tags: ["work", "focus", "productivity"],
    timeSuggestion: "anytime",
    estimatedMinutes: 120,
    popularity: 0,
    featured: true,
  },
  {
    name: "Inbox Zero",
    description: "Clear all emails from your inbox",
    category: "Productivity",
    icon: "envelope.badge.fill",
    color: "#3B82F6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["work", "email", "organization"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },
  {
    name: "Plan Tomorrow",
    description: "Prepare your tasks for the next day",
    category: "Productivity",
    icon: "calendar",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["planning", "organization", "evening"],
    timeSuggestion: "evening",
    estimatedMinutes: 10,
    popularity: 0,
    featured: true,
  },
  {
    name: "Learn Something New",
    description: "Spend time learning a new skill",
    category: "Productivity",
    icon: "book.fill",
    color: "#10B981",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["learning", "growth", "education"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: true,
  },
  {
    name: "Read for 30 Minutes",
    description: "Read books, articles, or educational content",
    category: "Productivity",
    icon: "book.pages",
    color: "#6366F1",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["reading", "learning", "growth"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },

  // ===== MINDFULNESS =====
  {
    name: "Gratitude Journal",
    description: "Write 3 things you're grateful for",
    category: "Mindfulness",
    icon: "heart.text.square.fill",
    color: "#EC4899",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["gratitude", "journaling", "mindfulness"],
    timeSuggestion: "evening",
    estimatedMinutes: 5,
    popularity: 0,
    featured: true,
  },
  {
    name: "Breathing Exercises",
    description: "5 minutes of focused breathing",
    category: "Mindfulness",
    icon: "wind",
    color: "#06B6D4",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["breathing", "relaxation", "mindfulness"],
    timeSuggestion: "anytime",
    estimatedMinutes: 5,
    popularity: 0,
    featured: false,
  },
  {
    name: "Digital Detox Hour",
    description: "One hour completely offline",
    category: "Mindfulness",
    icon: "wifi.slash",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "hard",
    tags: ["digital-detox", "mindfulness", "balance"],
    timeSuggestion: "evening",
    estimatedMinutes: 60,
    popularity: 0,
    featured: true,
  },
  {
    name: "Nature Time",
    description: "Spend time in nature",
    category: "Mindfulness",
    icon: "leaf.fill",
    color: "#10B981",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["nature", "outdoors", "wellness"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },

  // ===== EVENING ROUTINES =====
  {
    name: "No Screens Before Bed",
    description: "Avoid screens 1 hour before sleep",
    category: "Evening Routine",
    icon: "moon.zzz.fill",
    color: "#6366F1",
    frequency: "daily",
    targetCount: 1,
    difficulty: "hard",
    tags: ["sleep", "evening", "digital-detox"],
    timeSuggestion: "evening",
    estimatedMinutes: 60,
    popularity: 0,
    featured: true,
  },
  {
    name: "Skincare Routine",
    description: "Complete your evening skincare",
    category: "Evening Routine",
    icon: "sparkles",
    color: "#EC4899",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["selfcare", "evening", "health"],
    timeSuggestion: "evening",
    estimatedMinutes: 10,
    popularity: 0,
    featured: false,
  },
  {
    name: "Evening Reflection",
    description: "Reflect on your day and wins",
    category: "Evening Routine",
    icon: "moon.stars.fill",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["reflection", "evening", "journaling"],
    timeSuggestion: "evening",
    estimatedMinutes: 10,
    popularity: 0,
    featured: true,
  },
  {
    name: "Prepare Tomorrow's Outfit",
    description: "Choose and lay out tomorrow's clothes",
    category: "Evening Routine",
    icon: "tshirt.fill",
    color: "#F59E0B",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["organization", "evening", "planning"],
    timeSuggestion: "evening",
    estimatedMinutes: 5,
    popularity: 0,
    featured: false,
  },

  // ===== SOCIAL & RELATIONSHIPS =====
  {
    name: "Call a Friend/Family",
    description: "Connect with loved ones",
    category: "Social",
    icon: "phone.fill",
    color: "#EC4899",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["social", "relationships", "connection"],
    timeSuggestion: "anytime",
    estimatedMinutes: 15,
    popularity: 0,
    featured: false,
  },
  {
    name: "Acts of Kindness",
    description: "Do something kind for someone",
    category: "Social",
    icon: "heart.fill",
    color: "#EF4444",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["kindness", "social", "positivity"],
    timeSuggestion: "anytime",
    estimatedMinutes: null,
    popularity: 0,
    featured: true,
  },

  // ===== CREATIVITY =====
  {
    name: "Creative Writing",
    description: "Write creatively for 20 minutes",
    category: "Creativity",
    icon: "pencil.and.outline",
    color: "#F97316",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["writing", "creativity", "expression"],
    timeSuggestion: "anytime",
    estimatedMinutes: 20,
    popularity: 0,
    featured: false,
  },
  {
    name: "Draw or Paint",
    description: "Create visual art",
    category: "Creativity",
    icon: "paintbrush.fill",
    color: "#F97316",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["art", "creativity", "expression"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },
  {
    name: "Play Music",
    description: "Practice an instrument",
    category: "Creativity",
    icon: "music.note",
    color: "#8B5CF6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "medium",
    tags: ["music", "creativity", "skill"],
    timeSuggestion: "anytime",
    estimatedMinutes: 30,
    popularity: 0,
    featured: false,
  },

  // ===== FINANCE =====
  {
    name: "Track Expenses",
    description: "Log all expenses for the day",
    category: "Finance",
    icon: "dollarsign.circle.fill",
    color: "#14B8A6",
    frequency: "daily",
    targetCount: 1,
    difficulty: "easy",
    tags: ["finance", "budgeting", "organization"],
    timeSuggestion: "evening",
    estimatedMinutes: 5,
    popularity: 0,
    featured: false,
  },
  {
    name: "Review Budget",
    description: "Check your budget and spending",
    category: "Finance",
    icon: "chart.pie.fill",
    color: "#14B8A6",
    frequency: "weekly",
    targetCount: 1,
    difficulty: "medium",
    tags: ["finance", "budgeting", "planning"],
    timeSuggestion: "anytime",
    estimatedMinutes: 20,
    popularity: 0,
    featured: false,
  },
];
